#!/usr/bin/env python3
"""Regenerate hypotheses/INDEX.md from every hypothesis file's frontmatter.

Each hypothesis file is a markdown doc with YAML frontmatter between two
`---` markers. This reads every `H*.md` in the directory (excluding INDEX.md),
sorts by id, and writes a table with columns: id, status, title, linked_sweeps,
updated.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, Dict, List


HERE = Path(__file__).resolve().parent
INDEX_PATH = HERE / "INDEX.md"
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _parse_frontmatter(text: str) -> Dict[str, Any]:
    """Minimal YAML-ish frontmatter parser (flat key: value + list blocks).

    Avoids a PyYAML dep so this script stays runnable from any env.
    """
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    body = m.group(1)
    out: Dict[str, Any] = {}
    current_list_key: str | None = None
    for raw in body.splitlines():
        line = raw.rstrip()
        if not line:
            continue
        if current_list_key and line.lstrip().startswith("- "):
            out[current_list_key].append(line.lstrip()[2:].strip())
            continue
        current_list_key = None
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val == "[]":
            out[key] = []
        elif val == "":
            out[key] = []
            current_list_key = key
        elif val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            out[key] = [s.strip() for s in inner.split(",")] if inner else []
        else:
            out[key] = val
    return out


def _collect() -> List[Dict[str, Any]]:
    records = []
    for p in sorted(HERE.rglob("H*.md")):
        if p.name == "INDEX.md":
            continue
        text = p.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        fm["_path"] = str(p.relative_to(HERE))
        records.append(fm)
    return records


def _row(r: Dict[str, Any]) -> str:
    hid = r.get("id", "?")
    status = r.get("status", "?")
    title = r.get("title", "")
    sweeps = r.get("linked_sweeps") or []
    sweeps_cell = ", ".join(sweeps) if sweeps else "—"
    updated = r.get("updated", "")
    path = r.get("_path", "")
    return f"| [`{hid}`]({path}) | `{status}` | {title} | {sweeps_cell} | {updated} |"


def _render(records: List[Dict[str, Any]]) -> str:
    primary = [r for r in records if not r.get("parent")]
    children_by_parent: Dict[str, List[Dict[str, Any]]] = {}
    for r in records:
        parent = r.get("parent")
        if parent:
            children_by_parent.setdefault(parent, []).append(r)

    lines = [
        "# Hypothesis registry",
        "",
        "Auto-generated by `hypotheses/rebuild_index.py`.",
        "Edit hypothesis files directly, then rerun `python hypotheses/rebuild_index.py`.",
        "",
        "## Primary hypotheses",
        "",
        "| id | status | title | linked sweeps | updated |",
        "|----|--------|-------|---------------|---------|",
    ]
    for r in primary:
        lines.append(_row(r))
        hid = r.get("id", "")
        kids = children_by_parent.get(hid, [])
        if kids:
            lines.append("")
            lines.append(f"### Sub-probes of `{hid}`")
            lines.append("")
            lines.append("| id | status | title | linked sweeps | updated |")
            lines.append("|----|--------|-------|---------------|---------|")
            for k in kids:
                lines.append(_row(k))
            lines.append("")

    orphans = [r for r in records if r.get("parent") and r["parent"] not in {p.get("id") for p in primary}]
    if orphans:
        lines.append("## Orphaned sub-probes (parent missing)")
        lines.append("")
        lines.append("| id | status | title | linked sweeps | updated |")
        lines.append("|----|--------|-------|---------------|---------|")
        for r in orphans:
            lines.append(_row(r))
        lines.append("")

    lines.append("## Legend")
    lines.append("")
    lines.append("- `open` — active, no verdict yet")
    lines.append("- `ready` — infra-unblocked, awaiting run")
    lines.append("- `supported` — evidence accumulated across ≥ 1 sweep; cite in report")
    lines.append("- `refuted` — evidence against; stop pursuing")
    lines.append("- `stalled` — blocked on infra or unrelated work")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    records = _collect()
    if not records:
        print("no hypothesis files found", file=sys.stderr)
        return 1
    out = _render(records)
    INDEX_PATH.write_text(out, encoding="utf-8")
    print(f"wrote {INDEX_PATH} ({len(records)} hypotheses)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
