#!/usr/bin/env python3
"""Regenerate hypotheses/INDEX.md from every hypothesis file's frontmatter.

Each hypothesis file is a markdown doc with YAML frontmatter between two
`---` markers. This reads every `H*.md` in the directory (excluding INDEX.md),
sorts by id, and writes a table with columns: id, status, title, linked_sweeps,
updated.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, Dict, List


HERE = Path(__file__).resolve().parent
INDEX_PATH = HERE / "INDEX.md"
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _parse_frontmatter(text: str) -> Dict[str, Any]:
    """Minimal YAML-ish frontmatter parser (flat key: value + list blocks).

    Avoids a PyYAML dep so this script stays runnable from any env.
    """
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    body = m.group(1)
    out: Dict[str, Any] = {}
    current_list_key: str | None = None
    for raw in body.splitlines():
        line = raw.rstrip()
        if not line:
            continue
        if current_list_key and line.lstrip().startswith("- "):
            out[current_list_key].append(line.lstrip()[2:].strip())
            continue
        current_list_key = None
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val == "[]":
            out[key] = []
        elif val == "":
            out[key] = []
            current_list_key = key
        elif val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            out[key] = [s.strip() for s in inner.split(",")] if inner else []
        else:
            out[key] = val
    return out


def _collect() -> List[Dict[str, Any]]:
    records = []
    for p in sorted(HERE.glob("H*.md")):
        if p.name == "INDEX.md":
            continue
        text = p.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        fm["_path"] = p.name
        records.append(fm)
    return records


def _render(records: List[Dict[str, Any]]) -> str:
    lines = [
        "# Hypothesis registry",
        "",
        "Auto-generated by `hypotheses/rebuild_index.py`.",
        "Edit hypothesis files directly, then rerun `python hypotheses/rebuild_index.py`.",
        "",
        "| id | status | title | linked sweeps | updated |",
        "|----|--------|-------|---------------|---------|",
    ]
    for r in records:
        hid = r.get("id", "?")
        status = r.get("status", "?")
        title = r.get("title", "")
        sweeps = r.get("linked_sweeps") or []
        sweeps_cell = ", ".join(sweeps) if sweeps else "—"
        updated = r.get("updated", "")
        path = r.get("_path", "")
        lines.append(f"| [`{hid}`]({path}) | `{status}` | {title} | {sweeps_cell} | {updated} |")
    lines.append("")
    lines.append("## Legend")
    lines.append("")
    lines.append("- `open` — active, no verdict yet")
    lines.append("- `supported` — evidence accumulated across ≥ 1 sweep; cite in report")
    lines.append("- `refuted` — evidence against; stop pursuing")
    lines.append("- `stalled` — blocked on infra or unrelated work")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    records = _collect()
    if not records:
        print("no hypothesis files found", file=sys.stderr)
        return 1
    out = _render(records)
    INDEX_PATH.write_text(out, encoding="utf-8")
    print(f"wrote {INDEX_PATH} ({len(records)} hypotheses)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
